### ISSUE TITLE
error while recombining

### ISSUE THREAD

**Issue by StefanoCecere** [darkfall/MagicaVoxelUnity#10]
Unity 2017.1

when i try to recompine a selection of separated voxels, i get this error:

`NullReferenceException: Object reference not set to an instance of an object
MVVoxelChunk.get_sizeX () (at Assets/MagicaVoxel/Scripts/MVImporter.cs:28)
MVVoxModelVoxelInspector.CombineVoxels (.MVVoxModelVoxel[] voxels) (at Assets/MagicaVoxel/Scripts/Editor/MVVoxModelVoxelInspector.cs:38)
MVVoxModelVoxelInspector.OnInspectorGUI () (at Assets/MagicaVoxel/Scripts/Editor/MVVoxModelVoxelInspector.cs:20)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1240)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by barraudf** [comment]
Hi,

While trying to figure out what is going on, I came across a few NullReferenceExceptions too, fixed them and made a PR ( #11 ).

Not sure this will fix your problem though.

Did you try to load your model again?

**Comment by StefanoCecere** [comment]
no errors after this patch. thank you!
