### ISSUE TITLE
Interested in continuing to work on this?

### ISSUE THREAD

**Issue by kenny-evitt** [darkfall/MagicaVoxelUnity#5]
I've got questions, proposed changes, etc., but if you're not interested in working on this then I'll just play with my fork of this repo.

**Comment by kenny-evitt** [comment]
I just imported the Unity package for this into my project and Unity warns me "API Update Required". I chose the automatic update option and no other prompts were shown. But some of the items/components don't seem to have to been added correctly so I'm unsure if importing the package was the correct way to install this in my project.

When I open the supplied _Test1_ scene all of the objects are shown colored magenta – I'm guessing that's related to the scripts not being found or the shaders not compiling.

**Comment by kenny-evitt** [comment]
The missing scripts and 'broken' shaders seem like broken (relative?) paths given that I was able to fix the shaders (and materials?) by selecting appropriate-seeming options among the imported items.

**Comment by darkfall** [comment]
@kenny-evitt Please feel free to play with your fork. I haven't touched the code for a long time and may not touch it until sometime later due to my current job. I would be glad to merge PRs .

**Comment by kenny-evitt** [comment]
@darkfall Thanks!
